security:
  oauth2:
    client:
      client-id: gavin
      client-secret: gavin
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      grant-type: password
      scope: xxx
      registered-redirect-uri: http://localhost:8180/user
    resource:
      user-info-uri: http://localhost:8080/oauth/user
      token-info-uri: http://localhost:8080/oauth/check_token
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token
server:
  port: 8180
  servlet:
    session:
      cookie:
        name: gavinsession
logging:
  level:
    org.springframework.security: debug